#1 Sprint 9
Sintsoft/java-filmorate pull request #3
Opened 2023-03-06 06:36 UTC by Sintsoft

Made initial code for project

2023-03-06 08:35 UTC, LexLippi requested changes
Привет!

Неплохая работа, но есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!!!

2023-03-06 08:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Здесь можно добавить модификатор `final`, указывающий на то, что эта коллекция не может быть реинициализирована, таким образом ее поведение становится куда более предсказуемым

2023-03-06 08:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getId() > filmIdIterator - 1) {
Если коллекция `films` не содержит идентификатор фильма, то это тоже выглядит как ошибка, попытка обновить ещё не сохраненный фильм

2023-03-06 08:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getId() != 0) {
А почему в контроллере с фильмами проверка другая?
Может здесь стоит заложить аналогичную проверку?

2023-03-06 08:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
Также замечания аналогичные `FilmController`

2023-03-06 08:35 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Для этого можно использовать специальный класс `java.time.Duration`

2023-03-06 08:35 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +}
Тестов маловато:

1. должны быть ещё тесты на валидацию пользователя
2. должны быть тесты на валидацию фильма
3. Странно написан тест, ты сначала проверяешь, что создание класса породит `NPE`, а потом делаешь это снова, зачем?

2023-03-06 11:06 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private Map<Integer, Film> films = new HashMap<>();
Сделано

2023-03-06 11:07 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getId() > filmIdIterator - 1) {
Сделано

2023-03-06 15:13 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Сделано

2023-03-07 07:54 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2023-03-07 16:15 UTC, merged