Add friends likes
Sintsoft/java-filmorate pull request #4
Opened 2023-03-23 16:30 UTC by Sintsoft

New functional

2023-03-26 07:37 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    // }
Такие комментарии не стоит сохранять в коде, если кто-то оставляет такие комментарии в своем коде, то чаще всего потом бывает:

1. сложно прорваться к сути, так как полфайла закомментировано и код перемежается такими комментариями
2. участники проекта перестают обращать внимание на важные комментарии, и могут сделать что-то противоречащее важным комментариям. Поэтому после отладки стоит оставлять только смысловые комментарии

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmService filmService;
Этому полю не помешал быть модификатор доступа `final`, чтобы во время `runtime`,  никто не мог изменить используемый сервис.

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private UserService userService;
Аналогично про модификатор доступа

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        // }
Про комментарии уже писал

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    private UserStorage userStorage;
Стоит добавить модификатор `final`

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    private int filmIdIterator = 1;
Вот это необходимо перенести в класс хранилище, так как именно он отвечает за выдачу идентификаторов и их обновление. Сервис не знает, как внутри устроено хранилище, там может быть СУБД (и будет), которой вообще этот идентификатор не требуется, она сама будет его генерировать.

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        film.likeFilm(userId);
Почему `likeFilm`? Здесь же другое действие должно быть

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private int userIdIterator = 1;
Выше про это написал

2023-03-26 07:37 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserStorageTest.java
> +public abstract class UserStorageTest {
А почему этот класс абстрактный

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    Map<Integer, User> users = new HashMap<>();
Модификаторы доступа необходимы этому полю, иначе нарушается инкапсуляция

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    Map<Integer, Film> films = new HashMap<>();
Аналогично, необходимы модификаторы доступа

2023-03-26 07:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private User userNameCheck(User user) {
Это не просто `check`, в этом методе ты меняешь имя.
Лучше `chaeckAndUpdateUserName` или просто `updateUserName`

2023-03-26 08:55 UTC, Sintsoft commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserStorageTest.java
> +public abstract class UserStorageTest {
Потому, что может существовать несколько реализаций Storage, сейчас это InMemory, но потом будет БД, а основные методы останутся теми же.

2023-03-27 08:04 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    private int filmIdIterator = 1;
Если не будешь переделывать, то напиши почему, но в следющем спринте, все равно придется выпиливать это из сервиса :)

2023-03-27 08:05 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        Set<Film> sortedByLikes = new TreeSet<>(new FilmPopularityComparator());
Кстати, нет смысл создавать новый компаратор при каждом вызове метода, его можно сделать статическим полем класса.

2023-03-27 08:07 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ValidationException("Add film failed - invaild user");
Почему `invalid user`? Наверное `filmAlreadyExists`

2023-03-27 08:08 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    private UserService userService;
В тестах редко используют явные модификаторы доступа, они тут ни к чему

2023-03-27 17:10 UTC, LexLippi approved these changes
Отличная работа!

Желаю удачи в следующих спринтах!

2023-04-03 18:52 UTC, merged