Add database
Sintsoft/java-filmorate pull request #5
Opened 2023-04-21 22:54 UTC by Sintsoft

Сделал функционал. Есть несколько идей, буду рефакторить чать некрасивого кода в следующей ветке.

2023-04-22 09:52 UTC, LexLippi requested changes
Привет, неплохая работа!

Но с соединениями с СУБД надо работать аккуратнее!

Еще `GenreStorage` не помешал бы интерфейс.

Желаю удачи!

2023-04-22 09:52 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserStorageTests.java
> +        //testUser.setId(1);;
Это лучше удалить

2023-04-22 09:52 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTests.java
> +    private Validator validator;
В тестах лучше вообще не использовать модификаторы доступа, раз уж ты их не используешь у методов. Не стоит смешивать подходы, и то использовать, то не использовать

2023-04-22 09:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +	MPA_ID CHARACTER VARYING,
Могут быть `NULL`?

2023-04-22 09:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +	MPA_ID CHARACTER VARYING,
А ссылается эта колонка на какую?

2023-04-22 09:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +	EMAIL VARCHAR_IGNORECASE(256) NOT NULL,
Согласно RFC то поле может быть 320 символов длиной:

https://www.rfc-editor.org/errata/eid1690

2023-04-22 09:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +	BIRTHDAY DATE,
Может быть `NULL`?

2023-04-22 09:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +	NAME CHARACTER VARYING,
Может быть `NULL`?

2023-04-22 09:52 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/MPAStorage.java
> +        ) {
Это большая нагрузка создавать `connection` на каждый запрос. 
Можно передать управление соединениями `spring`, который будет сам принимать решение о созлании и закрытии соединений с СУБД

https://stackoverflow.com/questions/34303678/database-connection-expensive-to-create

2023-04-22 09:52 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
Это можно удалить, чтобы в дальнейшем не заниматься поддержкой, и не тратить лишнее время

2023-04-22 09:52 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +public class GenreStorage {
Замечания аналогичные `MPAStorage`

2023-04-22 19:18 UTC, Sintsoft commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTests.java
> +    private Validator validator;
done

2023-04-22 19:28 UTC, Sintsoft commented on src/main/resources/schema.sql
> +	MPA_ID CHARACTER VARYING,
Исправлено

2023-04-22 19:29 UTC, Sintsoft commented on src/main/resources/schema.sql
> +	MPA_ID CHARACTER VARYING,
Да, фильм может быть ещё не выпущен, он только заявлен и неизвестны ни дата выпуска, ни продолжительность

2023-04-22 19:39 UTC, Sintsoft commented on src/main/resources/schema.sql
> +	BIRTHDAY DATE,
Исправлено

2023-04-22 19:39 UTC, Sintsoft commented on src/main/resources/schema.sql
> +	NAME CHARACTER VARYING,
Исправлено

2023-04-23 22:18 UTC, Sintsoft commented on src/main/resources/schema.sql
> +	EMAIL VARCHAR_IGNORECASE(256) NOT NULL,
done

2023-04-23 22:18 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/MPAStorage.java
> +        ) {
Отрефкторил

2023-04-23 22:19 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +public class GenreStorage {
Сделано

2023-04-23 22:19 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
Удалил

2023-04-24 06:14 UTC, LexLippi requested changes
Привет!

Отличная работа!

Осталась пара маленьких доработок!

Желаю удачи!

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private final DBGenreStorage storage;
Здесь лучше использовать интерфейс `GenreStorage`, а не его реализацию

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +    JdbcTemplate jdbc;
А модификаторы доступа?

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +            }
В `qyeryForObject` можно передать `Genre.class`, и тогда на выходе сразу будет объект типа `Genre`, а не `Object`

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +        SqlRowSet resultSet = jdbc.queryForRowSet(GET_ALL_GENRES_QUERY);
Можно использовать `queryForList`
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#queryForList(java.lang.String,java.lang.Object%5B%5D,int%5B%5D,java.lang.Class)

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +        SqlRowSet resultSet = jdbc.queryForRowSet(GET_FILM_GENRES_QUERY, new Object[]{filmID});
Аналогично замечанию выше

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +            jdbc.update(
Можно использовать `batchUpdate`. Это лучше с точки зрения времени выполнения и нагрузки на СУБД

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +    }
В теории может понадобиться в каком-то еще `storage` и тогда удобнее будет вынести в отдельный класс, но пока можно оставить тут

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    JdbcTemplate jdbc;
Модификаторы доступа

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +public class DbFilmStorage implements FilmStorage {
Замечания аналогчные `GenreStorage`

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    private static final String GET_MOST_LIKED_FILMS_QUERY = "SELECT f.*, COUNT(l.USER_ID) AS AMOUNT\n" +
В запросе можно не добавлять переносы строк и табуляции. Лучше, чтобы это в коде читаемо выглядело, а СУБД скушает его и без этих тонкостей

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +public class DbUserStorage implements UserStorage {
Замечания аналогичные `FilmStorage`

2023-04-24 06:14 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/MPAStorage.java
> +public class MPAStorage {
Замечания аналогичные `GenreStorage`

2023-04-24 06:34 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private final DBGenreStorage storage;
Исправлено

2023-04-24 06:42 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +            }
Исправлено

2023-04-24 06:42 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +        SqlRowSet resultSet = jdbc.queryForRowSet(GET_ALL_GENRES_QUERY);
Исправлено

2023-04-24 06:42 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/DBGenreStorage.java
> +        SqlRowSet resultSet = jdbc.queryForRowSet(GET_FILM_GENRES_QUERY, new Object[]{filmID});
Исправлено

2023-04-24 07:21 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    JdbcTemplate jdbc;
Исправлено

2023-04-24 07:33 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +public class DbUserStorage implements UserStorage {
Исправлено

2023-04-24 07:35 UTC, Sintsoft commented on src/main/java/ru/yandex/practicum/filmorate/storage/MPAStorage.java
> +public class MPAStorage {
Исправлено

2023-04-25 06:39 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2023-04-25 07:20 UTC, merged